import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function TileC(props) {
  const { nodes, materials } = useGLTF('/tileC.glb')
  console.log(materials);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials['Wood.010']}
        position={[0, 0.35, 0]}
        scale={[1, 0.1, 1]}
        >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials['Material.001']}
          position={[0, -2, 0]}
          scale={[0.95, 1, 0.95]}
        />
        <group
          position={[-0.553, 1.002, -0.167]}
          rotation={[0, 1.545, 0]}
          scale={[0.25, 2.5, 0.25]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube218.geometry}
            material={materials['Main.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube218_1.geometry}
            material={materials['Walls.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube218_2.geometry}
            material={materials['Stone.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube218_3.geometry}
            material={materials['Wood.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube218_4.geometry}
            material={materials['Wood_Light.004']}
          />
        </group>
        <group
          position={[0.521, 0.996, -0.085]}
          rotation={[0, -1.531, 0]}
          scale={[0.25, 2.5, 0.25]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube074.geometry}
            material={materials['Main.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube074_1.geometry}
            material={materials['Walls.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube074_2.geometry}
            material={materials['Stone.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube074_3.geometry}
            material={materials['Wood.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube074_4.geometry}
            material={materials['Wood_Light.004']}
          />
        </group>
        <group
          position={[0.502, 0.902, 0.312]}
          rotation={[Math.PI, -1.531, Math.PI]}
          scale={[0.25, 2.5, 0.25]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube075.geometry}
            material={materials['Main.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube075_1.geometry}
            material={materials['Walls.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube075_2.geometry}
            material={materials['Stone.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube075_3.geometry}
            material={materials['Wood.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube075_4.geometry}
            material={materials['Wood_Light.004']}
          />
        </group>
        <group
          position={[-0.388, 0.944, 0.533]}
          rotation={[-Math.PI, 0.344, -Math.PI]}
          scale={[0.25, 2.5, 0.25]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube076.geometry}
            material={materials['Main.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube076_1.geometry}
            material={materials['Walls.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube076_2.geometry}
            material={materials['Stone.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube076_3.geometry}
            material={materials['Wood.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube076_4.geometry}
            material={materials['Wood_Light.004']}
          />
        </group>
        <group position={[0.206, 0.864, 0.618]} rotation={[0, 0.031, 0]} scale={[0.25, 2.5, 0.25]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube071.geometry}
            material={materials['Main.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube071_1.geometry}
            material={materials['Wood.006']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube071_2.geometry}
            material={materials['Wood_Light.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube071_3.geometry}
            material={materials['Walls.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube071_4.geometry}
            material={materials['Stone.006']}
          />
        </group>
        <group position={[-0.618, 0.914, 0.378]} rotation={[0, -1.454, 0]} scale={[0.3, 3, 0.3]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube073.geometry}
            material={materials['Main.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube073_1.geometry}
            material={materials['Wood.006']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube073_2.geometry}
            material={materials['Wood_Light.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube073_3.geometry}
            material={materials['Walls.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube073_4.geometry}
            material={materials['Stone.006']}
          />
        </group>
        <group position={[-0.023, 0.964, -0.02]} scale={[0.25, 2.5, 0.25]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube081.geometry}
            material={materials['Wood_Light.007']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube081_1.geometry}
            material={materials['Wood.010']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube081_2.geometry}
            material={materials.Gold}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube081_3.geometry}
            material={materials['Stone.010']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube081_4.geometry}
            material={materials.Metal_Light}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube081_5.geometry}
            material={materials['Green.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube081_6.geometry}
            material={materials.Yellow}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube081_7.geometry}
            material={materials.Red}
          />
        </group>
        <group position={[-0.003, 0.875, -0.59]} scale={[0.25, 2.5, 0.25]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube072.geometry}
            material={materials['Wood.007']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube072_1.geometry}
            material={materials['Wood_Light.006']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube072_2.geometry}
            material={materials['Stone.007']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube072_3.geometry}
            material={materials['Stone_Light.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube072_4.geometry}
            material={materials['Main.006']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube072_5.geometry}
            material={materials['Walls.004']}
          />
        </group>
        <group position={[0.503, 0.969, -0.533]} rotation={[0, -0.71, 0]} scale={[0.35, 3.5, 0.35]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube070.geometry}
            material={materials.Stone_Light}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube070_1.geometry}
            material={materials['Main.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube070_2.geometry}
            material={materials['Stone.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube070_3.geometry}
            material={materials['Wood_Light.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube070_4.geometry}
            material={materials['Wood.003']}
          />
        </group>
        <group
          position={[-0.618, 1.085, -0.601]}
          rotation={[0, 0.861, 0]}
          scale={[0.35, 3.5, 0.35]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder.geometry}
            material={materials['Walls.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_1.geometry}
            material={materials['Main.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_2.geometry}
            material={materials['Stone.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_3.geometry}
            material={materials['Wood.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_4.geometry}
            material={materials.Fabric}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_5.geometry}
            material={materials['Stone_Light.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_6.geometry}
            material={materials['Wood_Light.003']}
          />
        </group>
      </mesh>
    </group>
  )
}

useGLTF.preload('/tileC.glb')
