import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const TileL = React.forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF('/tileL.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.755, 0.389, 0.804]} rotation={[0, 0.77, 0]} scale={0.25}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube291.geometry}
          material={materials['Stone_Light.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube291_1.geometry}
          material={materials['Stone.011']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube291_2.geometry}
          material={materials['Wood.011']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube291_3.geometry}
          material={materials['Main.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube291_4.geometry}
          material={materials['Wood_Light.008']}
        />
      </group>
      <group position={[0.775, 0.389, -0.776]} rotation={[-Math.PI, 0.827, -Math.PI]} scale={0.25}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube290.geometry}
          material={materials['Stone_Light.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube290_1.geometry}
          material={materials['Stone.011']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube290_2.geometry}
          material={materials['Wood.011']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube290_3.geometry}
          material={materials['Main.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube290_4.geometry}
          material={materials['Wood_Light.008']}
        />
      </group>
      <group position={[0.329, 0.448, -0.004]} rotation={[-Math.PI, 1.568, -Math.PI]} scale={0.42}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube289.geometry}
          material={materials.Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube289_1.geometry}
          material={materials['Stone_Light.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube289_2.geometry}
          material={materials['Stone.009']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube289_3.geometry}
          material={materials['Wood.009']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube289_4.geometry}
          material={materials['Main.007']}
        />
      </group>
      <group position={[0.538, 0.442, 0.598]} rotation={[0, -0.767, 0]} scale={[0.42, 0.33, 0.43]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube288.geometry}
          material={materials['Stone.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube288_1.geometry}
          material={materials['Stone_Light.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube288_2.geometry}
          material={materials['Wood.008']}
        />
      </group>
      <group position={[0.547, 0.442, -0.576]} rotation={[0, 0.742, 0]} scale={[0.4, 0.33, 0.45]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube287.geometry}
          material={materials['Stone.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube287_1.geometry}
          material={materials['Stone_Light.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube287_2.geometry}
          material={materials['Wood.008']}
        />
      </group>
      <group position={[-0.385, 0.436, 0.267]} scale={0.3}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder037.geometry}
          material={materials['Wood.015']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder037_1.geometry}
          material={materials.Green}
        />
      </group>
      <group position={[-0.045, 0.436, 0.092]} scale={0.3}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder036.geometry}
          material={materials['Wood.015']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder036_1.geometry}
          material={materials.Green}
        />
      </group>
      <group position={[-0.066, 0.435, -0.008]} scale={0.3}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder035.geometry}
          material={materials['Wood.015']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder035_1.geometry}
          material={materials.Green}
        />
      </group>
      <group position={[-0.328, 0.438, -0.16]} scale={0.3}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder034.geometry}
          material={materials['Wood.015']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder034_1.geometry}
          material={materials.Green}
        />
      </group>
      <group position={[0.807, 0.446, 0.539]} rotation={[0, 0.019, 0]} scale={0.18}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube286.geometry}
          material={materials['Main.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube286_1.geometry}
          material={materials['Wood.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube286_2.geometry}
          material={materials['Wood_Light.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube286_3.geometry}
          material={materials['Walls.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube286_4.geometry}
          material={materials['Stone.006']}
        />
      </group>
      <group position={[0.819, 0.446, -0.442]} rotation={[0, 0.019, 0]} scale={0.18}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube285.geometry}
          material={materials['Main.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube285_1.geometry}
          material={materials['Wood.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube285_2.geometry}
          material={materials['Wood_Light.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube285_3.geometry}
          material={materials['Walls.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube285_4.geometry}
          material={materials['Stone.006']}
        />
      </group>
      <group position={[0.626, 0.446, -0.321]} rotation={[0, 0.019, 0]} scale={0.18}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube284.geometry}
          material={materials['Main.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube284_1.geometry}
          material={materials['Wood.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube284_2.geometry}
          material={materials['Wood_Light.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube284_3.geometry}
          material={materials['Walls.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube284_4.geometry}
          material={materials['Stone.006']}
        />
      </group>
      <group position={[0.617, 0.446, 0.365]} rotation={[0, 0.019, 0]} scale={0.18}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube283.geometry}
          material={materials['Main.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube283_1.geometry}
          material={materials['Wood.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube283_2.geometry}
          material={materials['Wood_Light.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube283_3.geometry}
          material={materials['Walls.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube283_4.geometry}
          material={materials['Stone.006']}
        />
      </group>
      <group position={[0.738, 0.449, -0.261]} rotation={[Math.PI, -1.518, Math.PI]} scale={0.18}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube282.geometry}
          material={materials['Main.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube282_1.geometry}
          material={materials['Walls.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube282_2.geometry}
          material={materials['Stone.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube282_3.geometry}
          material={materials['Wood.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube282_4.geometry}
          material={materials['Wood_Light.004']}
        />
      </group>
      <group position={[0.723, 0.449, 0.324]} rotation={[Math.PI, -1.518, Math.PI]} scale={0.18}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube281.geometry}
          material={materials['Main.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube281_1.geometry}
          material={materials['Walls.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube281_2.geometry}
          material={materials['Stone.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube281_3.geometry}
          material={materials['Wood.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube281_4.geometry}
          material={materials['Wood_Light.004']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube026.geometry}
        material={materials['Material.002']}
        position={[0, 0.15, 0]}
        rotation={[0, -1.569, 0]}
        scale={[0.95, 0.1, 0.95]}
      />
      <group position={[-0.353, 0.454, -0.089]} scale={0.3}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube052.geometry}
          material={materials.Wood_Light}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube052_1.geometry}
          material={materials['Wood.004']}
        />
      </group>
      <group position={[-0.385, 0.45, -0.068]} scale={0.3}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube051.geometry}
          material={materials['Wood.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube051_1.geometry}
          material={materials.Metal_Light}
        />
      </group>
      <group position={[0, 0.35, 0]} scale={[1, 0.1, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017.geometry}
          material={materials['Grass.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_1.geometry}
          material={materials['City_floor.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_2.geometry}
          material={materials['Road.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_3.geometry}
          material={materials['City_edge.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_4.geometry}
          material={materials['Grass_edge.001']}
        />
      </group>
    </group>
  )
})

useGLTF.preload('/tileL.glb')

export default TileL