import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const TileH = React.forwardRef((props, ref) => {
    const { nodes, materials } = useGLTF('/tileH.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.35, 0]} scale={[1, 0.1, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube222.geometry}
          material={materials.City_floor}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube222_1.geometry}
          material={materials.Grass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube222_2.geometry}
          material={materials.Grass_edge}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube222_3.geometry}
          material={materials['City_edge.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube022.geometry}
          material={materials['Material.003']}
          position={[0, -2, 0]}
          scale={[0.95, 1, 0.95]}
        />
        <group
          position={[0.766, 0.99, 0.32]}
          rotation={[Math.PI, -1.531, Math.PI]}
          scale={[0.18, 1.8, 0.18]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube002.geometry}
            material={materials['Main.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube002_1.geometry}
            material={materials['Walls.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube002_2.geometry}
            material={materials['Stone.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube002_3.geometry}
            material={materials['Wood.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube002_4.geometry}
            material={materials['Wood_Light.001']}
          />
        </group>
        <group
          position={[0.774, 0.99, -0.265]}
          rotation={[Math.PI, -1.531, Math.PI]}
          scale={[0.18, 1.8, 0.18]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube003.geometry}
            material={materials['Main.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube003_1.geometry}
            material={materials['Walls.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube003_2.geometry}
            material={materials['Stone.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube003_3.geometry}
            material={materials['Wood.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube003_4.geometry}
            material={materials['Wood_Light.001']}
          />
        </group>
        <group position={[-0.775, 0.99, -0.32]} rotation={[0, 1.531, 0]} scale={[0.18, 1.8, 0.18]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube004.geometry}
            material={materials['Main.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube004_1.geometry}
            material={materials['Walls.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube004_2.geometry}
            material={materials['Stone.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube004_3.geometry}
            material={materials['Wood.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube004_4.geometry}
            material={materials['Wood_Light.001']}
          />
        </group>
        <group position={[-0.783, 0.99, 0.265]} rotation={[0, 1.531, 0]} scale={[0.18, 1.8, 0.18]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube005.geometry}
            material={materials['Main.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube005_1.geometry}
            material={materials['Walls.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube005_2.geometry}
            material={materials['Stone.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube005_3.geometry}
            material={materials['Wood.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube005_4.geometry}
            material={materials['Wood_Light.001']}
          />
        </group>
        <group position={[0.661, 0.952, 0.363]} rotation={[0, 0.031, 0]} scale={[0.18, 1.8, 0.18]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube006.geometry}
            material={materials['Main.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube006_1.geometry}
            material={materials['Wood.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube006_2.geometry}
            material={materials['Wood_Light.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube006_3.geometry}
            material={materials['Walls.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube006_4.geometry}
            material={materials['Stone.002']}
          />
        </group>
        <group position={[0.661, 0.952, -0.324]} rotation={[0, 0.031, 0]} scale={[0.18, 1.8, 0.18]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube007.geometry}
            material={materials['Main.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube007_1.geometry}
            material={materials['Wood.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube007_2.geometry}
            material={materials['Wood_Light.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube007_3.geometry}
            material={materials['Walls.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube007_4.geometry}
            material={materials['Stone.002']}
          />
        </group>
        <group position={[0.852, 0.952, -0.446]} rotation={[0, 0.031, 0]} scale={[0.18, 1.8, 0.18]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube008.geometry}
            material={materials['Main.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube008_1.geometry}
            material={materials['Wood.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube008_2.geometry}
            material={materials['Wood_Light.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube008_3.geometry}
            material={materials['Walls.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube008_4.geometry}
            material={materials['Stone.002']}
          />
        </group>
        <group position={[0.852, 0.952, 0.534]} rotation={[0, 0.031, 0]} scale={[0.18, 1.8, 0.18]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube009.geometry}
            material={materials['Main.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube009_1.geometry}
            material={materials['Wood.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube009_2.geometry}
            material={materials['Wood_Light.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube009_3.geometry}
            material={materials['Walls.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube009_4.geometry}
            material={materials['Stone.002']}
          />
        </group>
        <group
          position={[-0.67, 0.952, -0.363]}
          rotation={[Math.PI, -0.031, Math.PI]}
          scale={[0.18, 1.8, 0.18]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube010.geometry}
            material={materials['Main.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube010_1.geometry}
            material={materials['Wood.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube010_2.geometry}
            material={materials['Wood_Light.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube010_3.geometry}
            material={materials['Walls.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube010_4.geometry}
            material={materials['Stone.002']}
          />
        </group>
        <group
          position={[-0.67, 0.952, 0.323]}
          rotation={[Math.PI, -0.031, Math.PI]}
          scale={[0.18, 1.8, 0.18]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube011.geometry}
            material={materials['Main.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube011_1.geometry}
            material={materials['Wood.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube011_2.geometry}
            material={materials['Wood_Light.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube011_3.geometry}
            material={materials['Walls.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube011_4.geometry}
            material={materials['Stone.002']}
          />
        </group>
        <group
          position={[-0.861, 0.952, 0.446]}
          rotation={[Math.PI, -0.031, Math.PI]}
          scale={[0.18, 1.8, 0.18]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube012.geometry}
            material={materials['Main.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube012_1.geometry}
            material={materials['Wood.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube012_2.geometry}
            material={materials['Wood_Light.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube012_3.geometry}
            material={materials['Walls.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube012_4.geometry}
            material={materials['Stone.002']}
          />
        </group>
        <group
          position={[-0.861, 0.952, -0.534]}
          rotation={[Math.PI, -0.031, Math.PI]}
          scale={[0.18, 1.8, 0.18]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube013_1.geometry}
            material={materials['Main.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube013_2.geometry}
            material={materials['Wood.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube013_3.geometry}
            material={materials['Wood_Light.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube013_4.geometry}
            material={materials['Walls.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube013_5.geometry}
            material={materials['Stone.002']}
          />
        </group>
        <group position={[0.579, 0.915, -0.578]} rotation={[0, 0.755, 0]} scale={[0.4, 3.3, 0.45]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube014.geometry}
            material={materials['Stone.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube014_1.geometry}
            material={materials['Stone_Light.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube014_2.geometry}
            material={materials['Wood.003']}
          />
        </group>
        <group position={[0.585, 0.915, 0.596]} rotation={[0, -0.754, 0]} scale={[0.42, 3.3, 0.43]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube015.geometry}
            material={materials['Stone.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube015_1.geometry}
            material={materials['Stone_Light.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube015_2.geometry}
            material={materials['Wood.003']}
          />
        </group>
        <group
          position={[-0.588, 0.915, 0.577]}
          rotation={[Math.PI, -0.755, Math.PI]}
          scale={[0.4, 3.3, 0.45]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube016.geometry}
            material={materials['Stone.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube016_1.geometry}
            material={materials['Stone_Light.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube016_2.geometry}
            material={materials['Wood.003']}
          />
        </group>
        <group
          position={[-0.594, 0.915, -0.597]}
          rotation={[-Math.PI, 0.754, -Math.PI]}
          scale={[0.42, 3.3, 0.43]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube017.geometry}
            material={materials['Stone.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube017_1.geometry}
            material={materials['Stone_Light.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube017_2.geometry}
            material={materials['Wood.003']}
          />
        </group>
        <group
          position={[0.368, 0.982, -0.003]}
          rotation={[-Math.PI, 1.556, -Math.PI]}
          scale={[0.42, 4.2, 0.42]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube018.geometry}
            material={materials['Metal.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube018_1.geometry}
            material={materials['Stone_Light.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube018_2.geometry}
            material={materials['Stone.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube018_3.geometry}
            material={materials['Wood.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube018_4.geometry}
            material={materials['Main.003']}
          />
        </group>
        <group
          position={[-0.377, 0.982, 0.002]}
          rotation={[0, -1.556, 0]}
          scale={[0.42, 4.2, 0.42]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube019.geometry}
            material={materials['Metal.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube019_1.geometry}
            material={materials['Stone_Light.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube019_2.geometry}
            material={materials['Stone.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube019_3.geometry}
            material={materials['Wood.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube019_4.geometry}
            material={materials['Main.003']}
          />
        </group>
        <group
          position={[0.804, 0.388, -0.78]}
          rotation={[-Math.PI, 0.839, -Math.PI]}
          scale={[0.25, 2.5, 0.25]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube020.geometry}
            material={materials['Stone_Light.006']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube020_1.geometry}
            material={materials['Stone.007']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube020_2.geometry}
            material={materials['Wood.007']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube020_3.geometry}
            material={materials['Main.006']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube020_4.geometry}
            material={materials['Wood_Light.003']}
          />
        </group>
        <group position={[0.804, 0.388, 0.8]} rotation={[0, 0.782, 0]} scale={[0.25, 2.5, 0.25]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube022_1.geometry}
            material={materials['Stone_Light.006']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube022_2.geometry}
            material={materials['Stone.007']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube022_3.geometry}
            material={materials['Wood.007']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube022_4.geometry}
            material={materials['Main.006']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube022_5.geometry}
            material={materials['Wood_Light.003']}
          />
        </group>
        <group position={[-0.813, 0.388, 0.78]} rotation={[0, -0.839, 0]} scale={[0.25, 2.5, 0.25]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube023.geometry}
            material={materials['Stone_Light.006']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube023_1.geometry}
            material={materials['Stone.007']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube023_2.geometry}
            material={materials['Wood.007']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube023_3.geometry}
            material={materials['Main.006']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube023_4.geometry}
            material={materials['Wood_Light.003']}
          />
        </group>
        <group
          position={[-0.813, 0.388, -0.8]}
          rotation={[Math.PI, -0.782, Math.PI]}
          scale={[0.25, 2.5, 0.25]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube024.geometry}
            material={materials['Stone_Light.006']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube024_1.geometry}
            material={materials['Stone.007']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube024_2.geometry}
            material={materials['Wood.007']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube024_3.geometry}
            material={materials['Main.006']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube024_4.geometry}
            material={materials['Wood_Light.003']}
          />
        </group>
      </group>
    </group>
  )
})

useGLTF.preload('/tileH.glb')

export default TileH