import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function TileD(props) {
  const { nodes, materials } = useGLTF('/tileD.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials.Material}
        position={[1.583, 0.15, 0.02]}
        scale={[0.95, 0.1, 0.95]}
      />
      <group position={[1.583, 0.35, 0.02]} scale={[1, 0.1, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_1.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_2.geometry}
          material={materials['Stone_Light.001']}
        />
      </group>
      <group position={[2.33, 0.449, 0.333]} rotation={[Math.PI, -1.531, Math.PI]} scale={0.18}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube082.geometry}
          material={materials['Main.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube082_1.geometry}
          material={materials['Walls.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube082_2.geometry}
          material={materials['Stone.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube082_3.geometry}
          material={materials['Wood.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube082_4.geometry}
          material={materials['Wood_Light.004']}
        />
      </group>
      <group position={[2.337, 0.449, -0.252]} rotation={[Math.PI, -1.531, Math.PI]} scale={0.18}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube083.geometry}
          material={materials['Main.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube083_1.geometry}
          material={materials['Walls.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube083_2.geometry}
          material={materials['Stone.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube083_3.geometry}
          material={materials['Wood.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube083_4.geometry}
          material={materials['Wood_Light.004']}
        />
      </group>
      <group position={[2.224, 0.445, 0.376]} rotation={[0, 0.031, 0]} scale={0.18}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube084.geometry}
          material={materials['Main.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube084_1.geometry}
          material={materials['Wood.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube084_2.geometry}
          material={materials['Wood_Light.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube084_3.geometry}
          material={materials['Walls.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube084_4.geometry}
          material={materials['Stone.006']}
        />
      </group>
      <group position={[2.416, 0.445, -0.434]} rotation={[0, 0.031, 0]} scale={0.18}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube086.geometry}
          material={materials['Main.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube086_1.geometry}
          material={materials['Wood.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube086_2.geometry}
          material={materials['Wood_Light.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube086_3.geometry}
          material={materials['Walls.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube086_4.geometry}
          material={materials['Stone.006']}
        />
      </group>
      <group position={[2.416, 0.445, 0.546]} rotation={[0, 0.031, 0]} scale={0.18}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube087.geometry}
          material={materials['Main.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube087_1.geometry}
          material={materials['Wood.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube087_2.geometry}
          material={materials['Wood_Light.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube087_3.geometry}
          material={materials['Walls.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube087_4.geometry}
          material={materials['Stone.006']}
        />
      </group>
      <group position={[2.142, 0.442, -0.565]} rotation={[0, 0.755, 0]} scale={[0.4, 0.33, 0.45]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube077.geometry}
          material={materials['Stone.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube077_1.geometry}
          material={materials['Stone_Light.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube077_2.geometry}
          material={materials['Wood.008']}
        />
      </group>
      <group position={[2.148, 0.442, 0.609]} rotation={[0, -0.754, 0]} scale={[0.42, 0.33, 0.43]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube080.geometry}
          material={materials['Stone.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube080_1.geometry}
          material={materials['Stone_Light.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube080_2.geometry}
          material={materials['Wood.008']}
        />
      </group>
      <group position={[1.931, 0.448, 0.01]} rotation={[-Math.PI, 1.556, -Math.PI]} scale={0.42}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube079.geometry}
          material={materials.Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube079_1.geometry}
          material={materials['Stone_Light.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube079_2.geometry}
          material={materials['Stone.009']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube079_3.geometry}
          material={materials['Wood.009']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube079_4.geometry}
          material={materials['Main.007']}
        />
      </group>
      <group position={[2.367, 0.389, -0.768]} rotation={[-Math.PI, 0.839, -Math.PI]} scale={0.25}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube088.geometry}
          material={materials['Stone_Light.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube088_1.geometry}
          material={materials['Stone.011']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube088_2.geometry}
          material={materials['Wood.011']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube088_3.geometry}
          material={materials['Main.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube088_4.geometry}
          material={materials['Wood_Light.008']}
        />
      </group>
      <group position={[2.367, 0.389, 0.812]} rotation={[0, 0.782, 0]} scale={0.25}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={materials['Stone_Light.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_1.geometry}
          material={materials['Stone.011']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_2.geometry}
          material={materials['Wood.011']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_3.geometry}
          material={materials['Main.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_4.geometry}
          material={materials['Wood_Light.008']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/tileD.glb')

export default TileD