import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const TileS = React.forwardRef((props, ref) => {
    const { nodes, materials } = useGLTF('/tileS.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.35, 0]} scale={[1, 0.1, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube428.geometry}
          material={materials.Grass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube428_1.geometry}
          material={materials.City_floor}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube428_2.geometry}
          material={materials.Road}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube428_3.geometry}
          material={materials.City_edge}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube428_4.geometry}
          material={materials.Grass_edge}
        />
        <group position={[-0.728, 1.002, 0.395]} scale={[0.3, 3, 0.3]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube179.geometry}
            material={materials['Wood.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube179_1.geometry}
            material={materials.Metal_Light}
          />
        </group>
        <group position={[-0.845, 1.044, 0.299]} scale={[0.3, 3, 0.3]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube180.geometry}
            material={materials.Wood_Light}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube180_1.geometry}
            material={materials['Wood.004']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube056.geometry}
          material={materials['Material.002']}
          position={[0, -2, 0]}
          scale={[0.95, 1, 0.95]}
        />
        <group position={[-0.815, 0.924, 0.391]} rotation={[0, 0.855, 0]} scale={[0.1, 1, 0.1]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube181.geometry}
            material={materials.Stone}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube181_1.geometry}
            material={materials.Wood}
          />
        </group>
        <group
          position={[0.122, 0.86, -0.329]}
          rotation={[Math.PI, -0.563, Math.PI]}
          scale={[0.15, 1.2, 0.15]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube174.geometry}
            material={materials['Wood.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube174_1.geometry}
            material={materials['Wood_Light.001']}
          />
        </group>
        <group
          position={[-0.088, 0.86, -0.394]}
          rotation={[-Math.PI, 0.596, -Math.PI]}
          scale={[0.15, 1.2, 0.15]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube175.geometry}
            material={materials['Wood.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube175_1.geometry}
            material={materials['Wood_Light.001']}
          />
        </group>
        <group position={[0.663, 0.995, 0.01]} rotation={[0, -0.054, 0]} scale={[0.18, 1.8, 0.18]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube409.geometry}
            material={materials['Main.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube409_1.geometry}
            material={materials['Walls.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube409_2.geometry}
            material={materials['Stone.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube409_3.geometry}
            material={materials['Wood.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube409_4.geometry}
            material={materials['Wood_Light.004']}
          />
        </group>
        <group
          position={[-0.265, 0.995, 0.043]}
          rotation={[0, -0.054, 0]}
          scale={[0.18, 1.8, 0.18]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube410.geometry}
            material={materials['Main.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube410_1.geometry}
            material={materials['Walls.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube410_2.geometry}
            material={materials['Stone.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube410_3.geometry}
            material={materials['Wood.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube410_4.geometry}
            material={materials['Wood_Light.004']}
          />
        </group>
        <group
          position={[-0.119, 0.995, -0.738]}
          rotation={[0, -0.054, 0]}
          scale={[0.18, 1.8, 0.18]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube173.geometry}
            material={materials['Main.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube173_1.geometry}
            material={materials['Walls.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube173_2.geometry}
            material={materials['Stone.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube173_3.geometry}
            material={materials['Wood.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube173_4.geometry}
            material={materials['Wood_Light.004']}
          />
        </group>
        <group
          position={[-0.691, 0.995, -0.622]}
          rotation={[0, 0.501, 0]}
          scale={[0.18, 1.8, 0.18]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube176.geometry}
            material={materials['Main.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube176_1.geometry}
            material={materials['Walls.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube176_2.geometry}
            material={materials['Stone.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube176_3.geometry}
            material={materials['Wood.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube176_4.geometry}
            material={materials['Wood_Light.004']}
          />
        </group>
        <group
          position={[-0.776, 0.995, -0.444]}
          rotation={[-Math.PI, 1.567, -Math.PI]}
          scale={[0.18, 1.8, 0.18]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube177.geometry}
            material={materials['Main.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube177_1.geometry}
            material={materials['Walls.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube177_2.geometry}
            material={materials['Stone.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube177_3.geometry}
            material={materials['Wood.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube177_4.geometry}
            material={materials['Wood_Light.004']}
          />
        </group>
        <group
          position={[-0.769, 0.995, -0.225]}
          rotation={[-Math.PI, 1.567, -Math.PI]}
          scale={[0.18, 1.8, 0.18]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube178.geometry}
            material={materials['Main.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube178_1.geometry}
            material={materials['Walls.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube178_2.geometry}
            material={materials['Stone.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube178_3.geometry}
            material={materials['Wood.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube178_4.geometry}
            material={materials['Wood_Light.004']}
          />
        </group>
        <group
          position={[-0.256, 0.956, -0.723]}
          rotation={[0, 0.063, 0]}
          scale={[0.18, 1.8, 0.18]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube172.geometry}
            material={materials['Main.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube172_1.geometry}
            material={materials['Wood.006']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube172_2.geometry}
            material={materials['Wood_Light.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube172_3.geometry}
            material={materials['Walls.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube172_4.geometry}
            material={materials['Stone.006']}
          />
        </group>
        <group
          position={[0.297, 0.956, 0.137]}
          rotation={[-Math.PI, 1.554, -Math.PI]}
          scale={[0.18, 1.8, 0.18]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube411.geometry}
            material={materials['Main.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube411_1.geometry}
            material={materials['Wood.006']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube411_2.geometry}
            material={materials['Wood_Light.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube411_3.geometry}
            material={materials['Walls.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube411_4.geometry}
            material={materials['Stone.006']}
          />
        </group>
        <group
          position={[-0.325, 0.956, 0.087]}
          rotation={[-Math.PI, 1.554, -Math.PI]}
          scale={[0.18, 1.8, 0.18]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube412.geometry}
            material={materials['Main.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube412_1.geometry}
            material={materials['Wood.006']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube412_2.geometry}
            material={materials['Wood_Light.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube412_3.geometry}
            material={materials['Walls.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube412_4.geometry}
            material={materials['Stone.006']}
          />
        </group>
        <group
          position={[-0.445, 0.956, -0.106]}
          rotation={[-Math.PI, 1.554, -Math.PI]}
          scale={[0.18, 1.8, 0.18]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube413.geometry}
            material={materials['Main.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube413_1.geometry}
            material={materials['Wood.006']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube413_2.geometry}
            material={materials['Wood_Light.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube413_3.geometry}
            material={materials['Walls.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube413_4.geometry}
            material={materials['Stone.006']}
          />
        </group>
        <group
          position={[0.878, 0.956, -0.073]}
          rotation={[-Math.PI, 1.554, -Math.PI]}
          scale={[0.18, 1.8, 0.18]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube414.geometry}
            material={materials['Main.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube414_1.geometry}
            material={materials['Wood.006']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube414_2.geometry}
            material={materials['Wood_Light.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube414_3.geometry}
            material={materials['Walls.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube414_4.geometry}
            material={materials['Stone.006']}
          />
        </group>
        <group position={[0.426, 0.859, -0.711]} scale={[0.18, 1.8, 0.18]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube429.geometry}
            material={materials['Main.011']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube429_1.geometry}
            material={materials['Walls.007']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube429_2.geometry}
            material={materials['Stone.014']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube429_3.geometry}
            material={materials['Wood.016']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube429_4.geometry}
            material={materials['Wood_Light.012']}
          />
        </group>
        <group position={[0.171, 0.921, -0.07]} scale={[0.2, 2, 0.2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube415.geometry}
            material={materials['Wood_Light.009']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube415_1.geometry}
            material={materials['Wood.013']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube415_2.geometry}
            material={materials['Metal_Light.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube415_3.geometry}
            material={materials['Green.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube415_4.geometry}
            material={materials['Stone.013']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube415_5.geometry}
            material={materials['Yellow.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube415_6.geometry}
            material={materials['Red.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube415_7.geometry}
            material={materials['Gold.001']}
          />
        </group>
        <group position={[-0.556, 0.915, 0.579]} rotation={[0, 0.734, 0]} scale={[0.42, 3.3, 0.43]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube416.geometry}
            material={materials['Stone.008']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube416_1.geometry}
            material={materials['Stone_Light.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube416_2.geometry}
            material={materials['Wood.008']}
          />
        </group>
        <group
          position={[0.622, 0.915, 0.597]}
          rotation={[-Math.PI, 0.787, -Math.PI]}
          scale={[0.42, 3.3, 0.43]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube417.geometry}
            material={materials['Stone.008']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube417_1.geometry}
            material={materials['Stone_Light.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube417_2.geometry}
            material={materials['Wood.008']}
          />
        </group>
        <group position={[0.041, 0.982, 0.379]} scale={[0.42, 4.2, 0.42]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube418.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube418_1.geometry}
            material={materials['Stone_Light.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube418_2.geometry}
            material={materials['Stone.009']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube418_3.geometry}
            material={materials['Wood.009']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube418_4.geometry}
            material={materials['Main.007']}
          />
        </group>
        <group
          position={[-0.805, 0.388, 0.811]}
          rotation={[0, -0.828, 0]}
          scale={[0.25, 2.5, 0.25]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube419.geometry}
            material={materials['Stone_Light.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube419_1.geometry}
            material={materials['Stone.011']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube419_2.geometry}
            material={materials['Wood.011']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube419_3.geometry}
            material={materials['Main.008']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube419_4.geometry}
            material={materials['Wood_Light.008']}
          />
        </group>
        <group position={[0.831, 0.388, 0.808]} rotation={[0, 0.761, 0]} scale={[0.25, 2.5, 0.25]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube420.geometry}
            material={materials['Stone_Light.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube420_1.geometry}
            material={materials['Stone.011']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube420_2.geometry}
            material={materials['Wood.011']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube420_3.geometry}
            material={materials['Main.008']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube420_4.geometry}
            material={materials['Wood_Light.008']}
          />
        </group>
      </group>
    </group>
  )
})

useGLTF.preload('/tileS.glb')

export default TileS